# Example configuration to rotate log files and exceptions
#Neos:
#  Flow:
#    log:
#      psr3:
#        Neos\Flow\Log\PsrLoggerFactory:
#          systemLogger:
#            default:
#              class: Webandco\Logrotate\Log\Backend\RotateBackend
#              options:
#                compress: true
#                truncate: false
#          securityLogger:
#            default:
#              class: Webandco\Logrotate\Log\Backend\RotateBackend
#              options:
#                compress: true
#                truncate: false
#          sqlLogger:
#            default:
#              class: Webandco\Logrotate\Log\Backend\RotateBackend
#              options:
#                compress: true
#                truncate: false
#          i18nLogger:
#            default:
#              class: Webandco\Logrotate\Log\Backend\RotateBackend
#              options:
#                compress: true
#                truncate: false
#      throwables:
#        storageClass: Webandco\Logrotate\Log\ThrowableStorage\CleanupStorage
#        optionsByImplementation:
#          Webandco\Logrotate\Log\ThrowableStorage\CleanupStorage:
#            storagePath: '%FLOW_PATH_DATA%Logs/Exceptions'
#            maximumDirSize: 10485760
#            logFilesToKeep: 3
#            compress: true
#            compressedArchivesToKeep: 10
#            compressInterval: 'P1D'
#            compressionAlgorithm: 'gz'
#            archiveName:
#              prefix: 'Exceptions.'
#              dateTime: 'Y-m-d'
#              postfix: '.tar.gz'
#            # Pattern for archives of interest
#            archiveGlob: 'Exceptions.*.tar.gz'
#            # Pattern for files of interest
#            glob: '*.txt'
